name: Docker Image Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

#     - name: Set up Docker
#       run: |
#         sudo apt-get update
#         sudo apt-get install ca-certificates curl
#         sudo install -m 0755 -d /etc/apt/keyrings
#         sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
# #         sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
# #         sudo chmod a+r /etc/apt/keyrings/docker.asc

# # # Add the repository to Apt sources:
# #         echo \
# #             "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
# #             $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
# #         sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
# #         sudo apt-get update
        

    - name: Build Docker image
      run: |
        make build
